# Generated by Django 3.0.3 on 2020-02-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_results',
            name='executed_date',
            field=models.DateTimeField(null=True, verbose_name='date executed'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='completed_date',
            field=models.DateTimeField(null=True, verbose_name='date completed'),
        ),
    ]
